# Paceday Rules

## Guidelines

Project-specific AI guidelines live in `.ai/guidelines/`. The `CLAUDE.md` file is auto-generated by Laravel Boost — never edit it directly. Add or update guidelines in `.ai/guidelines/` instead.

## Architecture Conventions

- **Actions** are domain-specific operations. They encapsulate a single business operation and are the primary entry point for domain logic.
- **Jobs** are orchestrators. They coordinate multiple actions, handle sequencing, and manage cross-cutting concerns. They are not domain logic themselves.
